version: '3.7'

services:
  influxdb:
    image: influxdb:2.7.11
    container_name: InfluxDB
    ports:
      - "8086:8086"
    env_file:
      - ./gateway.conf
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
    volumes:
      - .influxdb:/var/lib/influxdb2

  grafana:
    image: grafana/grafana:11.6.1
    container_name: Grafana
    ports:
      - "3000:3000"
    env_file:
      - ./gateway.conf
    environment:
      - GF_SERVER_HTTP_ADDR=0.0.0.0
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb
    entrypoint: ["/bin/sh", "-c", "chown -R 472:472 /var/lib/grafana && /run.sh"]

  telegraf:
    image: telegraf:1.34.2
    container_name: Telegraf
    depends_on:
      - influxdb
    user: "999:0"
    env_file:
      - ./gateway.conf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc:/host/etc:ro

  basicstation:
    build:
      context: ./basicstation
      args:
        BASICSTATION_COMMIT: ba4f85d
    image: basicstation:2.0.6
    container_name: BasicStation
    devices:
      - /dev/spidev0.0:/dev/spidev0.0
    depends_on:
      - influxdb
    env_file:
      - ./gateway.conf
    restart: always