{
 "title": "Basic Dashboard",
 "refresh": "5s",
 "panels": [
  { "title": "LoRaWAN Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Devices Seen",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"piwan\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => \n      (r._measurement == \"mqtt_consumer\") and \n      r._field == \"frame_count\"\n  )\n  |> group(columns: [\"device_id\"])\n  |> last()\n  |> keep(columns: [\"device_id\", \"_time\"])\n  |> rename(columns: {_time: \"Last Seen\", device_id: \"Device ID\"})\n  |> group()"
    }
   ]
  },
  {
   "title": "Received Packet Log",
   "type": "logs",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 1 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\n\ndata = from(bucket: \"piwan\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  // include both measurements in one stream\n  |> filter(fn: (r) =>\n      r._measurement == \"mqtt_consumer\"\n  )\n\ndata\n  |> pivot(\n      rowKey: [\"_time\"],\n      columnKey: [\"_field\"],\n      valueColumn: \"_value\"\n  )\n  |> filter(fn: (r) => exists r.device_id and exists r.payload)\n  |> map(fn: (r) => ({\n      _time:        r._time,\n      _value:       string(v: r._time) \n                   + \" | \" + r.device_id \n                   + \" | \" + r.payload,\n      device_id:    r.device_id,\n      frame_count:  r.frame_count,\n      received_at:  r.received_at,\n      rssi:         r.rssi,\n      snr:          r.snr,\n      payload:      r.payload,\n      decoded_bytes:r.decoded_bytes\n  }))"
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"piwan\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n      r._measurement == \"mqtt_consumer\" and \n      r._field == \"rssi\"\n  )\n  |> group(columns: [\"device_id\"])      // ← group by device\n  |> keep(columns: [\"device_id\", \"_value\", \"_time\"]) "
    }
   ]
  },
  {
   "title": "SNR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"piwan\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n      r._measurement == \"mqtt_consumer\" and \n      r._field == \"snr\"\n  )\n  |> group(columns: [\"device_id\"])      // ← group by device\n  |> keep(columns: [\"device_id\", \"_value\", \"_time\"]) "
    }
   ]
  },
  { "title": "Gateway Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "RPi Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"piwan\")\n  |> range(start: -5m)\n  |> filter(fn: (r) =>\n    r._measurement == \"system\" and\n    r._field == \"uptime\"\n  )\n  |> last()\n  |> map(fn: (r) => ({\n    _time: r._time,\n    uptime_hours: float(v: r._value)\n  }))"
    }
   ]
  },
  {
   "title": "Container uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"piwan\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._field == \"uptime_ns\" \n  )\n  |> map(fn: (r) => ({\n      r with\n      _value: float(v: r._value) / 1000000000.0\n  }))\n  |> group(columns: [\"container_name\"])\n  |> keep(columns: [\"_time\", \"_value\", \"container_name\"])\n  |> yield(name: \"Uptime (hrs)\")"
    }
   ]
  },
  {
   "title": "Container versions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"piwan\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n       r._measurement == \"docker_container_status\" and\n       r._field == \"uptime_ns\"\n     )\n  |> group(columns: [\"container_name\"])\n  |> last()\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r.container_version,\n      container_name: r.container_name\n  }))\n  |> keep(columns: [\"_value\", \"container_name\"])"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "cpu",
     "query": "from(bucket: \"piwan\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"cpu\" and\n    r._field == \"usage_idle\" and\n    r.cpu != \"cpu-total\"\n  )\n  |> map(fn: (r) => ({\n    r with\n    _value: 100.0 - r._value,\n    _field: \"\"\n  }))\n  |> aggregateWindow(every: 1m, fn: mean)\n  |> drop(columns: [\"host\"])\n  |> yield(name: \"CPU Usage\")",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "disk",
     "query": "from(bucket: \"piwan\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"disk\" and\n    r._field == \"used_percent\" and\n    r.path == \"/host/etc\"\n  )\n  |> aggregateWindow(every: 1m, fn: mean)\n  |> yield(name: \"disk_used_percent\")",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "mem",
     "query": "from(bucket: \"piwan\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"mem\" and\n    r._field == \"used_percent\"\n  )\n  |> aggregateWindow(every: 1m, fn: mean)\n  |> map(fn: (r) => ({\n    r with _field: \"Memory Usage (%)\"\n  }))\n  |> drop(columns: [\"host\"])\n  |> yield(name: \"Memory Usage\")",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}